### ISSUE TITLE
Access logs for apps hosted in a shiny server

### ISSUE THREAD

**Issue by williamlai2** [dreamRs/shinylogs#14]
Hi, this is probably similar to #5. `shinylogs` works fine locally, but there does not seem to be any output anywhere when in shiny server. How do you access the logs? What settings should I be using? I have admin access and have had a look in the usual places including the log folder for the particular app.

**Comment by pvictor** [comment]
Which storage mode did you use ?

For saving logs as Json files, you can do something like: 

```r
track_usage(storage_mode = store_json(path = "/var/log/shinylogs"))
```

and make sure : 
* path exist
* is writeable, change permissions if needed

Then logs will be available in that folder

**Comment by williamlai2** [comment]
Yes, that seems to work. I was just using `track_usage(storage_mode = store_json(path = "logs/"))` initially. 

I changed it as per your advice. Created the folder then changed the `chmod` permissions. Thanks.
