### ISSUE TITLE
Installation error - Nanotime

### ISSUE THREAD

**Issue by samuelmf1** [dreamRs/shinylogs#27]
Hi, 

Having trouble installing the package due to a failure with Nanotime dependency. This install force uninstalls Nanotime and then attempts to recompile and install it, resulting in the following error:

`
Error: C++17 standard requested but CXX17 is not defined
* removing '/gpfs/commons/home/nsaravanan/R/x86_64-pc-linux-gnu-library/4.1/nanotime'
Warning in install.packages :
  installation of package 'nanotime' had non-zero exit status
ERROR: dependency 'nanotime' is not available for package 'shinylogs'
* removing '/gpfs/commons/home/nsaravanan/R/x86_64-pc-linux-gnu-library/4.1/shinylogs'
Warning in install.packages :
  installation of package 'shinylogs' had non-zero exit status
`

Would appreciate help resolving this - thanks!

**Comment by pvictor** [comment]
Hello,

It seems that your version of GCC does not support C++17, try to update it with your package manager:

```shell
sudo yum install -y gcc-c++
```

and then retry to install nanotime: 

```r
install.packages("nanotime")
```
