### ISSUE TITLE
vignette typo

### ISSUE THREAD

**Issue by tanho63** [dreamRs/shinylogs#3]
> storage_json() : store logs has separate JSON files (one by session).
> storage_rds() : store logs has individually RDS files (one by session).
> storage_sqlite() : store logs in a SQLite database.
> storage_json() : don’t store logs, print them in R console.

This last one I think should be `storage_null()`, right?

**Comment by pvictor** [comment]
Absolutely, thank you for noticing, it's fixed!

Victor
