### ISSUE TITLE
timestamp should keep fractions of seconds

### ISSUE THREAD

**Issue by phgrosjean** [dreamRs/shinylogs#6]
Hi,

Nice package. However, `shiny logs:::get_timestamp()` uses `format(time, format = "%Y-%m-%dT%H:%M:%S%z")`, which truncates the timestamp down to second. This is not enough because two or more events can occur within a second.

Please, either use `format(time, format = "%Y-%m-%dT%H:%M:%OS3%z")`, or add an argument to `track_usage()`, like `time_format = "%Y-%m-%dT%H:%M:%S%z"`, so that we could change it by ourselves if we want.

Thanks,

Philippe

**Comment by phgrosjean** [comment]
Another (may be better) solution would be to expose `get_timestamp()` and allow to use our own function is a similar way as `get_user =` in `track_usage()`. This way, one could also use, e.g., `format(time, format = "%Y-%m-%d %H:%M:%OS6", tz = "GMT")` which is the most complete and unambiguous date format in GMT.

**Comment by phgrosjean** [comment]
It appears that the changes required are larger, including changes required in the JS code. So, I have submitted a pull request with tracking of time events down to the millisecond. Thanks for considering it.

Best,

Philippe

**Comment by pvictor** [comment]
Hello Philippe,

Thanks for this and the PR.

The `get_timestamp()` function is only used to store the information when server is connected, I thought that seconds were sufficient. For identifying session however I use package (`nanotime`)[https://github.com/eddelbuettel/nanotime].

Timestamp might be the same for two session but session ID will be different:

```r
aa <- bit64::as.integer64(nanotime::nanotime(a <- Sys.time()))
bb <- bit64::as.integer64(nanotime::nanotime(b <- Sys.time()))
a;b
# [1] "2020-09-04 09:11:01 CEST"
# [1] "2020-09-04 09:11:01 CEST"
identical(a, b)
# [1] FALSE
identical(format(a), format(b))
# [1] TRUE
identical(aa, bb)
# [1] FALSE
```

Am I mistaken ?

I have no objection, however, to change the format used in the function `get_timestamp` and in JavaScript code.


Victor

**Comment by phgrosjean** [comment]
Hello Victor,

You use `get_timestamp()` for start and stop of a session, indeed, and the Javascript dayjs for the other events. My proposal is to record the timestamp with a precision that would be enough to sort events in a chronological order, which is not possible if time is rounded to the nearest second as it is currently the case.
You don't need nanotime for that, I think. Successive calls to `Sys.time()` give different results (but not if formatted in a way that sub second information is lost, of course). See `identical(Sys.time(), Sys.time())`=> `FALSE` and `identical(format(Sys.time()), format(Sys.time()))` => `TRUE` (most of the time).

Best,

Philippe

**Comment by pvictor** [comment]
Yes I understand that, at the time it was not very important to me if someone was connected one second before or after one another, but I understand the need, and if we can be precise, we might as well be precise.

For identifying session, I think `nanotime` is important to be sure as much as possible that session are unique, see:

```r
format(Sys.time(), format = "%Y-%m-%d %H:%M:%OS3%z"); format(Sys.time(), format = "%Y-%m-%d %H:%M:%OS3%z")
# [1] "2020-09-04 10:52:02.087+0200"
# [1] "2020-09-04 10:52:02.087+0200"
nanotime::nanotime(Sys.time()); nanotime::nanotime(Sys.time())
# [1] 2020-09-04T08:52:02.088188+00:00
# [1] 2020-09-04T08:52:02.090178+00:00
```
In the rare case where two people connect to an application in the same millisecond ^^

I will review and accept the PR in the week-end.

Thanks,

Victor

**Comment by phgrosjean** [comment]
You are right with nanotime for the session id. Thanks for considering my PR.

Philippe
