### ISSUE TITLE
Recording switches between tabs/tabPanels

### ISSUE THREAD

**Issue by jejoenje** [dreamRs/shinylogs#8]
Hi there,
This is a great package, and looks incredibly useful - thank you.
I was wondering if there is an easy way of recording switches between "tabs", for example in those generated in the UI by `tabPanel()`? I don't see these recorded in the JSON log?
Thank you,
Jeroen

**Comment by pvictor** [comment]
Hello,

Thanks :) 

Yes you have to set an ID to `tabsetPanel` to record events, e.g. : 

```r
library(shiny)
library(shinylogs)

ui <- fluidPage(
  tabsetPanel(
    id = "MY_TABS",
    tabPanel("Plot", plotOutput("plot")),
    tabPanel("Summary", verbatimTextOutput("summary")),
    tabPanel("Table", tableOutput("table"))
  )
)

server <- function(input, output, session) {
  track_usage(
    storage_mode = store_null()
  )
  
}

shinyApp(ui, server)
```

Will gives when you change tabs: 

```json
{
  "name": "MY_TABS",
  "timestamp": "2020-12-07 17:12:29",
  "value": "Summary",
  "type": "",
  "binding": "shiny.bootstrapTabInput"
} 
{
  "name": "MY_TABS",
  "timestamp": "2020-12-07 17:12:32",
  "value": "Table",
  "type": "",
  "binding": "shiny.bootstrapTabInput"
} 
```

The first tab is not recorded since it's the default that user see, event is triggered if tab is changed.

Victor

**Comment by jejoenje** [comment]
Thanks so much for the super quick response, that is much appreciated.

This now works - thank you. I hadn't realised it needed an ID value, and was confusing myself where the ID would go (inside `tabSetPanel()` or `tabSet()`; plus I was trying to get it to work with nested tabs and `navbarPage()` on top of that.

For the record, the following works for recording switches to further nested tabSets as well as navbarPage - 

```
library(shiny)
library(shinylogs)

ui <- fluidPage(
  
  navbarPage(title = "test", id = "OUTER_TABS",
    tabPanel("MAIN1", 
      tabsetPanel(id = "INNER_TABS",
        tabPanel("INNER1", helpText("foo")),
        tabPanel("INNER2", helpText("bar"))          
      )       
    ),
    tabPanel("MAIN2", verbatimTextOutput("summary")),
    tabPanel("MAIN3", tableOutput("table"))
  )
  
  
)

server <- function(input, output, session) {
  track_usage(
    storage_mode = store_null()
  )
  
}

shinyApp(ui, server)
```

Best wishes
Jeroen

**Comment by pvictor** [comment]
Yes, that's it. This works because if you use an ID in `navbarPage` or `tabsetPanel` you can retrieve the selected item in server with `input$<ID>`.

Victor
